# Set language and version
language: python
python:
  - "3.6"

# Install dependencies
install: "pip install -r requirements.txt"

# Install required services
services:
  - redis-server

# Set environment variables
env:
  - REDIS_URL="redis://localhost:6379"

# Run tests
script: pytest
